INFO 2025-06-14 18:44:42,115 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 18:45:48,892 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 18:46:22,124 autoreload C:\Users\Andre\OneDrive\django\adeies\adeies\settings.py changed, reloading.
INFO 2025-06-14 18:46:22,656 autoreload C:\Users\Andre\OneDrive\django\adeies\adeies\settings.py changed, reloading.
INFO 2025-06-14 18:51:19,639 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 18:54:12,670 autoreload C:\Users\Andre\OneDrive\django\adeies\adeies\settings.py changed, reloading.
INFO 2025-06-14 18:54:14,479 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 20:09:00,101 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 20:09:02,999 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 20:10:04,153 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 20:10:06,247 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 20:11:53,916 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 20:11:55,033 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 20:13:12,479 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 20:13:13,718 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 20:27:36,731 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 20:27:38,988 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 20:27:46,374 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 20:27:47,523 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 20:35:54,797 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 20:35:55,626 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 20:36:11,226 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 20:36:12,426 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 20:43:32,389 autoreload C:\Users\Andre\OneDrive\django\adeies\users\models.py changed, reloading.
INFO 2025-06-14 20:43:33,336 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 20:46:10,221 autoreload C:\Users\Andre\OneDrive\django\adeies\users\models.py changed, reloading.
INFO 2025-06-14 20:46:11,208 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 20:53:57,801 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 20:53:58,508 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 21:05:10,155 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 21:05:11,137 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 21:07:44,987 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 21:07:46,148 autoreload Watching for file changes with StatReloader
ERROR 2025-06-14 21:14:28,692 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:16:11,060 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:17:12,525 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:18:31,217 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:20:54,584 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:21:55,265 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:23:07,453 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
INFO 2025-06-14 21:29:54,302 autoreload Watching for file changes with StatReloader
ERROR 2025-06-14 21:33:24,309 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
INFO 2025-06-14 21:35:42,966 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 21:35:44,160 autoreload Watching for file changes with StatReloader
ERROR 2025-06-14 21:35:54,433 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:38:01,032 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:39:47,933 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:40:14,918 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
INFO 2025-06-14 21:43:44,305 autoreload C:\Users\Andre\OneDrive\django\adeies\users\urls.py changed, reloading.
INFO 2025-06-14 21:43:45,376 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 21:44:35,201 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 21:44:36,371 autoreload Watching for file changes with StatReloader
ERROR 2025-06-14 21:46:29,243 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
INFO 2025-06-14 21:47:59,715 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 21:48:00,733 autoreload Watching for file changes with StatReloader
ERROR 2025-06-14 21:48:22,508 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
INFO 2025-06-14 21:54:24,847 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 21:54:26,362 autoreload Watching for file changes with StatReloader
ERROR 2025-06-14 21:54:41,891 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:55:21,984 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:55:22,004 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:56:43,046 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:57:23,346 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:57:23,361 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:58:10,141 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:58:34,011 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:58:34,062 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
INFO 2025-06-14 21:58:58,384 autoreload C:\Users\Andre\OneDrive\django\adeies\users\views.py changed, reloading.
INFO 2025-06-14 21:58:59,556 autoreload Watching for file changes with StatReloader
INFO 2025-06-14 21:59:15,190 autoreload C:\Users\Andre\OneDrive\django\adeies\users\urls.py changed, reloading.
INFO 2025-06-14 21:59:16,482 autoreload Watching for file changes with StatReloader
ERROR 2025-06-14 21:59:37,657 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 21:59:37,683 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 22:00:10,170 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 22:00:10,183 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 22:00:10,203 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-14 22:00:10,219 log Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Andre\OneDrive\django\adeies\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
INFO 2025-06-14 22:02:26,155 basehttp "GET / HTTP/1.1" 200 8160
